### ISSUE TITLE
Switching to a FULLY deterministic Linux state machine

### ISSUE THREAD

**Issue by 0xRampey** [d-roak/cosmos-linux#5]
Hey there! 
First of all, this is super cool and opened my eyes to what one can run on Cosmos SDK without breaking the 'determinism' variant.
On that note, do check out https://github.com/facebookexperimental/hermit. 

Hermit provides a fully deterministic Linux container where you are **guaranteed** to get the same output with a particular sequence of commands. That means, programs (smart contracts) in any language can be run and reproduced deterministically! 
Seems quite interesting and would be happy to help out here.

References:
- https://developers.facebook.com/blog/post/2022/11/22/hermit-deterministic-linux-testing/

**Comment by d-roak** [comment]
Will definitively look into it!
