### ISSUE TITLE
Devpost comments

### ISSUE THREAD

**Issue by d-roak** [d-roak/cosmos-linux#6]
"This is a great idea! I actually really like it as a potential model for chain-based cloud computing style workloads.

Effectively its something rollup like, without a state validity challenge scheme. But this isn't for asset custody, so its fine for the user to rely on reputation alone for validity verifications.

- Authorization structure for "updates" to a docker instance (new commands)
- DA for commands so anyone can in principle rebuild the instance. Makes sense that DA is the core thing to decentralize
- Queries can replay results + be signed by replying node, and you rely on signatures + reputation for authenticity. (Someday may become zk-verified)

the main question to me is how we gas meter updates"

by @ValarDragon

**Comment by 0xRampey** [comment]
One way to approach is this to follow Ethereum's gas metering style but replace `gas` with `execution time`.

For example, when a user initiates a tx, they specify a `time limit` (like gas limit) which is the maximum amount of time they are willing to run the Linux command for. The gas fees they pay for this is `Cost of compute = Execution time limit X Compute price`
If the operation runs for longer than the time limit, the transaction will fail, but the execution time will be used up. However if the operation finishes earlier, the remaining time is refunded back to the user (as a multiple of compute price)

Compute price here depends on the same factors that gas price does which is mainly demand (# of users, txs, long-running jobs) and supply (# of machines, execution timespace).

What might be a little tricky though is that `cost of compute` estimation needs to account for the hardware resources of the Docker instance to come up with a good measure of running/execution time.
